dist: trusty
language: node_js
node_js:
  - "6"
addons:
  firefox: "latest"

before_install:
  - cd frontend

install:
  - npm install

before_script:
  # Enable virtual screen to run karma browser tests
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run build
