language: node_js
node_js:
  - "4.3"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
  - ./travis/frontend2-install.sh

script:
  - ./travis/frontend2-build.sh
