language: node_js
node_js:
  - "6"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - pwd
  - cd frontend
install:
  - pwd
  - npm install

before_script:
  - pwd
  - cd frontend
script:
  - pwd
  - npm run build
