language: node_js
node_js:
  - "6"
env:
  - CXX=g++-4.8
addons:
  firefox: "46.0"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - cd frontend

install:
  - npm install

before_script:
  # Enable virtual screen to run Firefox for karma tests
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run build
